eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.23.1:8761/eureka/
    instance:
      hostname: 192.168.23.1
      
      
      
      
# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/
#     instance:
#       hostname: localhost
